### ISSUE TITLE
How to develop?, was: how to run locally?

### ISSUE THREAD

**Issue by paulvi** [zmandel/Plus-for-Trello#12]
Can you update README with (a link) how to develop locally this codebase

**Comment by zmandel** [comment]
its not possible to develop locally the content script of the chrome
extension. you must be online with access to trello.com

On Mon, Jan 9, 2017, 2:45 AM Paul Verest <notifications@github.com> wrote:

Can you update README with (a link) how to develop locally this codebase

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zmandel/Plus-for-Trello/issues/12>, or mute the thread

**Comment by paulvi** [comment]
well, locally was not right word.

How do develop this extension?

**Comment by zmandel** [comment]
see the google chrome extension developers guide. tldr; you load the
extension locally into chrome. for spreadsheet sync to work locally there
is additional setup needed.
finally, the GitHub code is not the latest. download the latest code by
using the "extension source code viewer" extension.
we also have a mobile directory in there for the mobile & web version (also
outdated in github)
cheers
zig

**Comment by paulvi** [comment]
This should be noted in README

**Comment by zmandel** [comment]
will do soon, and also update to the latest code. im in the process to
migrate to gulp and hide some secret keys from github (which is why i
stopped pushing to github)

**Comment by HugoHeneault** [comment]
I also have ideas of integrations of Trello calculated time to others services. I can't wait for the code update! 👍

**Comment by zmandel** [comment]
cool :)  in the meantime try this which lets you download a ZIP of the
latest source code (untouched  ).
https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin

in the short term I plan to add a feature to reports so it writes the
output to a text file (json/csv). That could be used for integrations with
external tools. Not sure if thats where you plan to go.

There is also the mobile and web app. Its also in github but also outdated.
The workarround for now is to get the latest one from
https://app.plusfortrello.com, where you can see the untouched source code
in the browser debugger or use a crawler to download the entire thing. it
runs in mobile, browser, locally and offline.

**Comment by HugoHeneault** [comment]
I will try it. 

We're looking for json report by user/board/list :)

**Comment by zmandel** [comment]
yeah it will support json, you will need to read it from the chrome
downloads folder after launching the report url.

**Comment by HugoHeneault** [comment]
Yeah, we'd like to make it use directly events from your app, instead of downloading/loading data

**Comment by zmandel** [comment]
aha, you would need to open the report window as a hidden popup, then post
s message to get the json.  another way is to trigger the "copy" button,
then read it from the clipboard.
