### ISSUE TITLE
Feature request: rest time countdown reminder

### ISSUE THREAD

**Issue by xgdgsc** [zmandel/Plus-for-Trello#14]
Usually after I finish the task for some time, I would want to take a break. If this extension can set to auto start a rest countdown timer after committing some work, and alert me to start working afterwards it would be very helpful. 

It would be even more helpful if it could block some websites during working timer and allow those during rest timer. 

Thanks!

**Comment by zmandel** [comment]
interesting. we have a similar request to remind users if a timer is not started after a certain time. seems this one could fit in that idea.

**Comment by xgdgsc** [comment]
You can take a look at the extension [Pomotodo](https://chrome.google.com/webstore/detail/pomotodo/algakdpepofkajponmledaldoloboinf/reviews?hl=en) for some of the functionality I mentioned. I used to like the infinite mode that auto starts after break. But running at fixed intervals everyday make me stressed out. I like the flexibility of plus for trello, but it seems not stressful enough for me to concentrate on work :smile:
