### ISSUE TITLE
Feature request: Duration sync with Calendar

### ISSUE THREAD

**Issue by AmauryVanEspen** [zmandel/Plus-for-Trello#20]
Good afternoon,

I would like to know how can I see the "estimate" as a duration of an event in Calendar.
I've recently read there is a Beta feature in Trello about Item due date in check list, but still not "duration" and link to iCalendar feed.

My needs is to set a duration for a card or a task according to its due date. Maybe a start date if available. 

I'm trying to understand where can I set the duration (estimate?) of an event (according to due date or start date if available) in the Calendar. (I mean my synchronise Google Calendar)

i've found :
Calendar (https://help.trello.com/article/811-viewing-cards-in-a-calendar-view) provides a feature to get an iCalendar feed

there is also Cronofy which sync calendar 2 ways, but still no duration

finally Planway, still no duration.

I'm still available to translate Plus for Trello in French if required as I did for the first version of Trello that I've translated in French also.

Thank you 

Amaury

**Comment by zmandel** [comment]
sorry, not something we can do from Plus.

**Comment by AmauryVanEspen** [comment]
Thank you for quick feedback !
