### ISSUE TITLE
Plus with Drive force me to accept API login every hours

### ISSUE THREAD

**Issue by tacosjs** [zmandel/Plus-for-Trello#21]
Not sure if it's plugin related or only chrome (I've taken a look, without success) but since I use stealth mode, an API (Identity API Scope Approval UI) popup prompt every hour or so to log back in. Any way to avoid that and stay connected?!

![image](https://user-images.githubusercontent.com/6282845/81410516-df4a9c80-910e-11ea-820f-2c6e044b04a5.png)

**Comment by zmandel** [comment]
make sure you are logged-in to chrome. we havent seen this issue before.

**Comment by tacosjs** [comment]
You were right! The problem is that my Chrome sync with another email. Have to swap the main account to the one used to sync and it now work perfectly! Gonna close but it might help someone else.
