### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by bardo** [zmandel/Plus-for-Trello#5]
In our team we have a mixed environment of Chrome and Firefox. It would be great to be able to use Plus without keeping more than one browser open. Is it planned in the future?

**Comment by zmandel** [comment]
The plan is to bring to Firefox a simpler version based on the mobile app. It will let you view card s/e and enter s/e.
However, we are not planning to bring the full reports/charts because of the huge architecure differences with firefox (basically firefox does not support background pages)

**Comment by bardo** [comment]
Thanks for replying. That would be a good start! Do you already have a draft timeline?

**Comment by zmandel** [comment]
not really. feature-wise it goes in this order:
android s/e bar, 
android timers & search
ios version (actually should be fairtly easy)
firefox basic version (features similar to mobile app: s/e bar & timers and view card s/e per user.)

however if you saw the g+ poll there is lots of interest in the "time in lists" feature and a future poll will decide that vs firefox.

**Comment by bardo** [comment]
Ok, thank you for the update. I'm now following you on G+ as well :)

**Comment by zmandel** [comment]
Firefox recently announced support for Chrome extensions, and some things work on the dev channel. We will make a firefox update once Firefox fully supports all our APIs.

**Comment by zmandel** [comment]
Firefox is delaying too much some critical APIs for us. Thus we made a basic version that runs on Firefox (desktop and mobile) from https://app.plusfortrello.com or the native Android app. We also hope soon Trello will approve our powerup which will make it much easier for Firefox (and Safari, Edge etc) to view and enter S/E from any card front. We plan to add basic reporting to those versions over time.

**Comment by sudokai** [comment]
Hi,

Firefox is transitioning to Webextensions (seemingly compatible with Chrome). I've seen many Chrome extensions ported to Firefox lately. Maybe it's time to revisit this issue?

Thank you for your hard work!

**Comment by zmandel** [comment]
Indeed! I revisited it yesterday, but Firefox wont support webSql in webextensions, which would make it a huge porting effort into something like lovefield. https://discourse.mozilla.org/t/webextension-apis-for-sql-storage/12224/2

**Comment by sudokai** [comment]
If you don't mind, I will fork this extension and try to port it. I'm completely new to extension development, but I really miss this extension on Firefox, so I'll give it a shot. Will open a PR if I succeed in porting it.

**Comment by zmandel** [comment]
your biggest hurdle will be porting the websql because firefox doesn't
support it. look at libraries that implement websql on top of indexedDb
otherwise it will be impossible to port.
