### ISSUE TITLE
Behaving erratically on my machine...

### ISSUE THREAD

**Issue by skd123us** [zmandel/Plus-for-Trello#6]
I have been using plus for trello for the last 4 months. I have hundreds of lists and each list has 5 to 6 plus! statements on the average.

In the last week or so it started behaving erratically. After trello loads, I have to wait for about one and half minutes till plus for trello loads. Sometimes it does not load at all.

I tried Reset button and reinstalling the extension it did not help. Maybe something is corrupted. I tried in another machine and seeing similar result.

Data corruption? Any ideas? 

so far I liked this tool, it does everything I can imagine :)

**Comment by zmandel** [comment]
thanks for the report. Are you using Chrome Canary by any chance?
There is another user with problems in Canary, however I have not received any other reports and thus cannot repro.
Can you look into the page "dev console" and also the "extension background dev console" ? Let me know if you need help finding those.

Corruption is very unlikely (has never happened to anyone so far)

**Comment by skd123us** [comment]
I am using regular chrome. Yesterday I found a few error messages in the background extension console. Usually what happens is most of the time it is pretty slow, say I am stopping the clock, it takes effect after 2 to 3 minutes. After about an hour or two it breaks down completely. 

Today morning as I started it came up fine but stopping the clock took some time. Here is the output. I will watch it during the day and attach more output if I see something different.

## Chrome console

'webkitURL' is deprecated. Please use 'URL' instead.

## Background extension console

sync: finished. delta prev:1436280939.41s
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:4 delta prev:0.83s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:8 delta prev:1.15s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0.02s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:8 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.03s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:2.11s
trellosync.js:6 sync: finished. delta prev:3.33s
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:0 delta prev:0.86s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:0.89s
trellosync.js:6 sync: finished. delta prev:10.67s
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:0 delta prev:0.76s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:0.78s

**Comment by zmandel** [comment]
hmm all those logs are ok. more questions:
does anything else get slow over time or just plus?
do the trello pages also get slow or just plus?
do all plus features get slow? (chrome plus menu, reports and burndown charts) or just actions inside a trello page? (clicking start or stop timer, entering s/e with the plus bar, loading s/e boxes in board view etc)

is your hard disk almost full?

please send me your email to support@plusfortrello.com and we can arrange a remote desktop debugging session.

**Comment by skd123us** [comment]
I am sending some more background log after the previous log, you will see that right now the sync is slow, some of them are more than 2 minutes (according to the log) however, I think that the actual time is more:

trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:0 delta prev:1.47s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:1.5s
**trellosync.js:6 sync: finished. delta prev:700.04s**
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:0 delta prev:0.95s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:0.98s
**trellosync.js:6 sync: finished. delta prev:10621.08s**
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:1 delta prev:0.84s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:1 delta prev:0.56s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:1 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:1.5s
trellosync.js:6 sync: finished. delta prev:3.01s
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:0 delta prev:0.78s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.02s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:0.85s
**trellosync.js:6 sync: finished. delta prev:177.2s**
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:0 delta prev:0.83s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:0 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:0.85s
**trellosync.js:6 sync: finished. delta prev:149.84s**
trellosync.js:6 sync: Stage 1 of 8: Starting sync total:1 delta prev:0s
trellosync.js:6 sync: Stage 2 of 8: Getting board history total:1 delta prev:0.79s
trellosync.js:6 sync: Stage 3 of 8: Pre-processing history total:1 delta prev:0.54s
trellosync.js:6 sync: Stage 4 of 8: Completing card details total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 5 of 8: Processing history total:1 delta prev:0s
trellosync.js:6 sync: Stage 6 of 8: Completing card's lists total:0 delta prev:0.01s
trellosync.js:6 sync: Stage 7 of 8: Completing list details total:0 delta prev:0s
trellosync.js:6 0 'NULL' idList
trellosync.js:6 0 'UNKNOWN' idList
trellosync.js:6 sync: Stage 8 of 8: Saving all total:1 delta prev:0.01s
trellosync.js:6 sync: finished. delta prev:1.42s

**Comment by skd123us** [comment]
To answer your previous question:

does anything else get slow over time or just plus?

> > Other sites work fine, however once in a while (maybe once a day or so), chrome gets locked up and response time decreases a lot. At that time I close all browser window and start chrome again.
> > Also once in a couple of days it gives error about adobe flask/shockwave and I just restart.

do the trello pages also get slow or just plus?

> > trello pages are fine, Note that trello is just a website and I do not have any extension for trello.

do all plus features get slow? (chrome plus menu, reports and burndown charts) or just actions inside a trello page? (clicking start or stop timer, entering s/e with the plus bar, loading s/e boxes in board view etc)

> > The trello icon at the top always shows the total time for the week, that always works. However, when I click on it, I see only the first line of links which does not work. So no report. However, after many minutes when plus loads they again show up.
> > 
> > When I click on a trello list, the top bar (where it shows time for every day, does not come up)
> > 
> > The trello clock button shows blank initially. It takes about 3 minutes to load. Then if I click on the button to stop the time, it does not work and clock keeps running. It does stop after 2 to three minutes.

Yesterday I saw lots of error messages in the background console. I will keep an eye.

> > forgot to mention computer hard disk has lot of space ~ 110 GB and also I have 8GB on a I7 processor laptop.

Let me tell you I like this tool so much that even though it is not working I am still using the plus! syntax to put my time in trello, I hope when it starts working, I will still have the information in plus :)

I am entering about 5 or 6 time entries every day so for a period of 3 months we have about 500 plus entries. Could this be the cause of my slowness?

**Comment by zmandel** [comment]
yes you will have the times there. but we need to figure out whats the root
cause of the problem. can we do a remote chrome desktop session?

**Comment by skd123us** [comment]
Yes sure... do you want to do it now. I never did chrome desktop session. Does it work across the firewall? I can also do a join.me session if you want.

**Comment by skd123us** [comment]
ok got chrome desktop installed, where can I send you the 12 digit code? I do not see how to send private message from github. I am in EST (Eastern Time), let me know when you want to do it.

**Comment by zmandel** [comment]
within the next 2 hours i will be able to get to a laptop. then you can
send the code to support@plusfortrello.com
