### ISSUE TITLE
just using one comment per card for sync

### ISSUE THREAD

**Issue by despairblue** [zmandel/Plus-for-Trello#7]
Hey, how about just using one comment (per person of course) per card for syncing and simply adding a line whenever a timing is added? That would reduce a lot of noise, since the only comment for trello plus would be somewhere at the bottom of the discussion.

And thanks for this wonderful extension :clap:

**Comment by zmandel** [comment]
if I understood it right, there would be a couple of issues with that approach:
1) there would be no "trustable" source of S/E change history as you would only have the latest total in trello. This is easy to tamper and also would not survive a "reset" of the data stored inside Chrome.

Plus S/E currently cannot be tampered with (in particular if the manager is the one entering all first estimates, as the produced card comment can only be modified by her).

2) trello API does not provide a way to detect changes in comments (eficiently that is, unless one re-reads the entire card comment history and backwards (newest to oldest) because trello does not provide forward, thus consuming a lot of bandwidth). This is also the reason why making a change to a card s/e comment is not picked up by Plus until you "reset sync".

**Comment by despairblue** [comment]
## 1

there would be a source of change, unless I don't get it:
Jane's (manager) comment:

```
plus! 0/2
```

John's comment:

```
plus! 1/0
plus! 1/0
```

The lines could also be extended with a datetime string.

## 2

That is true but it also holds true for using plus for trello from multiple computers. At least it didn't pick up the time I spent yesterday on another computer, probably because it doesn't crawl the comments the other computer's plus for trello added yesterday.

**Comment by zmandel** [comment]
for 1 i cant modify or change the order in card comments as it breaks
trello.

for 2, look closely. it does sync everything across devices. thats the
whole point of sync :)

**Comment by zmandel** [comment]
also what you ask about ordering is what you see if you click the "card
report" link

**Comment by despairblue** [comment]
Eh, why would you have to reorder the comments? :confused: 

What I'm proposing is more like the already implemented stealth google spreadsheet sync.

Jane plans the estemates of a card, PFT creates the following comment (note I added the time to the syntax):

```
!plus [07/25/2015 5:30:43] 0/2
```

John starts working on the card for an hour, PFT creates a comment for him:

```
!plus [07/25/2015 7:30:43] 1/0
```

Jane finishes it up, PFT edits her old comment by adding a line:

```
!plus [07/25/2015 5:30:43] 0/2
!plus [07/25/2015 13:30:43] 1/0
```

Card is done. No comments were harmed (reorded) in the process.

Fixing number 2 seems also possible. I'd imagine PFT keeps track of each card's last known comment so it does not have to read all comments again for syncing, right? So basically it would just keep doing that + remembering the comments already created for each user's time tracking purpose.

The problem I see now is, as you mentioned above, the API does not offer a method to request a specific comment. So PFT would have to traverse the comments from now on backwards until it finds all user's comments. This is a problem, true. : pensive:

**Comment by zmandel** [comment]
that would not work for a couple reasons:
1) like I mentioned, trello does not provide a way to efficiently detect
that a comment was edited. checking comments per board/card/user every time
would be overkill

2) its not safe. you are typing whatever time you want in there, and its
not relative to the comment timestamp. it also makes it harder to add/edit
times from other browsers or mobile app.

Its good that you are thinking about alternate ways thou. but they need to
be equal or better security-wise than what plus currently has. Im also
working now on a secure way to let users modify past s/e (thus 1st
estimates wont get disturbed when entry errors are made and so on)

note that in the end, what you really gain with your method is to clean the
comments area. But that could be addressed in other ways, for example plus
could provide a toggle to show/hide such comments. A long time ago I did
have sometjing like that but I had to remove it for performance reasons
when trello changed their layout code (back in mid 2014)

cheers,

Zig Mandel https://developers.google.com/experts/people/zig-mandel

**Comment by despairblue** [comment]
> note that in the end, what you really gain with your method is to clean the
> comments area. But that could be addressed in other ways, for example plus
> could provide a toggle to show/hide such comments. A long time ago I did
> have sometjing like that but I had to remove it for performance reasons
> when trello changed their layout code (back in mid 2014)

Yep, after thinking for a while I came to the same conclusion that that would be easier.

How does PFT retrieve new comments anyhow? `commentCard` per board? Or per card?

> the API does not offer a method to request a specific comment
> That was actually wrong.

https://trello.com/1/actions/55b3f247ad554896edcce01a does return a single comment. But still that would mean polling every known comment on every sync. Better than using `commentCard` but still not good enough.

**Comment by zmandel** [comment]
I don't use either because i infer all the info from incremental syncs of
board actions. if i cant reconstruct if from that history I then use the
other apis.
this is so syncs can be super quick.

**Comment by despairblue** [comment]
Oh yeah, probably a way to hide the comments would be an ideal solution. I see that the others won't work.
